### ISSUE TITLE
目前支持socks5协议代理吗?  

### ISSUE THREAD

**Issue by Stoptimerag** [spacemeowx2/switch-lan-play#102]
请问作者目前支持socks5协议代理吗。看了下readme上面是可选？
试了下，连接服务器的话仅支持no pass吗？ 加密模式和user：pass 怎么填写呢？

**Comment by Stoptimerag** [comment]
windows下运行的

.\lan-play-win64.exe --socks5-server-addr serverip:port（这里仅支持nopass ?server:port?）

**Comment by spacemeowx2** [comment]
仅支持no pass, 也就是建议你在localhost开socks5服务端, 远端开udp隧道有延迟可能有未预期行为

**Comment by Stoptimerag** [comment]
> 仅支持no pass, 也就是建议你在localhost开socks5服务端, 远端开udp隧道有延迟可能有未预期行为

本地开server没啥用啊，想着用您这个项目用作ps4加速用。
如果我本地开socks5服务端，那这流量还得想办法从我本机在转发一次到远端服务器是吧?

**Comment by spacemeowx2** [comment]
这很容易, 用sslocal就能搞定
