### ISSUE TITLE
90DNS not working after stopping the client

### ISSUE THREAD

**Issue by hrvylein** [spacemeowx2/switch-lan-play#114]
* start LAN-Play-Client and connect Switch to WLAN
* Run 90DNS-Checker -> all Ninty-Domains Blockes
* Close/Crash Lan-Play-Client
* Run 90Dns-Checker again: all Ninty-Domains are unblocked even tho DNS Resolution is really slow

This could lead to bans. Is it known why DNS servers aren't used when the lan-play-gateway dies? Is there an unknown fallback?

**Comment by spacemeowx2** [comment]
Could you show me the link to `90DNS-Checker`, not sure what you are referring to.

**Comment by spacemeowx2** [comment]
If you are saying https://github.com/meganukebmp/Switch_90DNS_tester/

I have looked into the source code. It seems to be false positive:

https://github.com/meganukebmp/Switch_90DNS_tester/blob/f9bd37c2ccc4a66bef843fea6db35f2431b947f1/source/main.c#L105-L125

When there is no resolve result, the function returns 1, and tell you it's unblocked.

**Comment by hrvylein** [comment]
Yeah, that's the homebrew I was talking about and good find! Will open an issue over there. Maybe he can add a message if dns resolving isn't working.
