### ISSUE TITLE
Is not 32 bit compatible?

### ISSUE THREAD

**Issue by gitHatmos** [spacemeowx2/switch-lan-play#12]
I tried to start it, but said "not have compatibility", I could not start it, if you have other necessary files etc, please let me know.
(sorry i use google translation)

**Comment by bao3** [comment]
@githatmos 
https://transfer.sh/MjWSh/lan-play_0.0.3_32.exe , This is 32bit version, it's unofficial  but I compiled myself .

**Comment by spacemeowx2** [comment]
I will update `.drone.yml` to compile 32bit version automatically

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/switch-lan-play/releases
