### ISSUE TITLE
Lan-play_win64.exe error The application was unable to start correctly

### ISSUE THREAD

**Issue by Adie256Gaming** [spacemeowx2/switch-lan-play#121]
I have installed npcap, but i got this error, please fix this
![v5](https://user-images.githubusercontent.com/80298910/115948096-326f5800-a4f6-11eb-863e-56dec7dff334.JPG)

**Comment by igromanru** [comment]
Try WinPcap instead.

**Comment by Adie256Gaming** [comment]
Okay, lemme try it
