### ISSUE TITLE
请问支持socks5的tcp协议吗？

### ISSUE THREAD

**Issue by DoubleCircle-Salt** [spacemeowx2/switch-lan-play#128]
我劫持到本地的socks5代理端，日志显示只收到udp的包，没有socks tcp请求的包

**Comment by DoubleCircle-Salt** [comment]
抱歉，这么久才回复。这两天我根据您说的，找方法验证了一下。
我用mac端模拟switch，作为客户端，配置了本地按照方法配置了ip和dns，本地用dig指令，是能成功获取到dns解析的。

**Comment by DoubleCircle-Salt** [comment]
另一台电脑启动了switch-lan-play，和ss-client，能够清楚地看到udp的日志，但看不到tcp的

**Comment by DoubleCircle-Salt** [comment]
我的switch-lan-play的启动方式是 `./lan-play-macos --socks5-server-addr 127.0.0.1:1080 `
1080是我本地ss-client的端口，请问哪里出了错吗？

**Comment by spacemeowx2** [comment]
你这个情况可以看看ps命令有没有残留的lan-play-macos进程。一个局域网内只能有一个lanplay进程，否则tcp会互相reset导致没有连接

**Comment by DoubleCircle-Salt** [comment]
谢谢回复，我验证一下。

**Comment by DoubleCircle-Salt** [comment]
你好，问题解决了。
是我网络的问题，我用我们公司的网络只能看到udp相关的日志，并且后来验证发现udp的包，根据目的地地址的不同，有的能回到机器上，有的不能（比如dns设置为113段的一个dns服务器就能解析，设置成114就不行）；
后来我换成用自己的iphone手机开热点，两台机器同时连热点，就都解决了。
可能是我们公司的路由器路由策略限制了，我准备研究一下，将switch-lan-play的网关换一个看看行不行。
