### ISSUE TITLE
interface not specified, opening all interfaces

### ISSUE THREAD

**Issue by Adie256Gaming** [spacemeowx2/switch-lan-play#129]
Interface not specified, opening all interfaces
[DEBUG]: open \Device\NPF_{8E1E93B7-F99B-4F74-B42E-92548D172BE3} fail: get mac
[DEBUG]: open \Device\NPF_{FFB86692-C16E-4C28-B9DD-4814FCC91F33} fail: get mac
[DEBUG]: open \Device\NPF_{4DFD3F8A-208A-4D93-843A-69877CF25B35} ok
[DEBUG]: open \Device\NPF_{B2938EC9-A95C-4DAE-89E6-636C0370F291} fail: get mac
[DEBUG]: open \Device\NPF_{15412BE4-1562-435E-9375-40452ABBA724} ok
[DEBUG]: open \Device\NPF_{EEFFE4CF-73F6-4BA8-9CFE-D7E5B5037562} ok
[DEBUG]: open \Device\NPF_Loopback fail: datalink(0)
[DEBUG]: open \Device\NPF_{482A7D64-0556-44B0-B737-1E90CA2686BB} ok

here the text on the cmd/lanplaywin64.exe

**Comment by qelix** [comment]
This is not a bug. If you specify your interface using the `--netif` flag (e.g. `lan-play --netif enp3s0`), it only opens the interface you need. I don't know how Windows interfaces work, so in your case it would probably be something like `lan-play --netif "\Device\NPF_{4DFD3F8A-208A-4D93-843A-69877CF25B35}"`. In practice, you don't need to worry about this, though.

**Comment by Adie256Gaming** [comment]
Ok, thank you for the information
