### ISSUE TITLE
Pretty sure switch firmware 14.0.0+broke this program.

### ISSUE THREAD

**Issue by Abro61209** [spacemeowx2/switch-lan-play#137]
Used to work flawlessly, I would configure the custom network settings, launch any game with idn_mitm or on a wire with a LAN capable game and get the IConnection message in the CMD, I don't get that at all now no matter what I try.

**Comment by kapiteinvanhetschip** [comment]
I really thinks the same did every possible way to get it to work but my switch wont connect to the program

**Comment by RealLenouche** [comment]
I want tested with :
Ldn_mitm : 1.13.0
FW : 14.1.1
Atmosphere : 1.3.2

Windows : The program work but dont show "IConnection::IConnection" message when I connect my switch :/

Linux (tested with other person same CFW+FW+Ldn_mitm) : Work without any problems

**Comment by drizuid** [comment]
For unknown reasons, some firmwares no longer show iConnection in the console but are still able to play. We have updated the official guide to address this, but simply put, if you set it up correctly, just try playing a game with a friend.
