### ISSUE TITLE
国行动森可以通过 switch-lan-play 让朋友远程上岛吗?

### ISSUE THREAD

**Issue by pdog18** [spacemeowx2/switch-lan-play#139]

**Comment by spacemeowx2** [comment]
配合ldn_mitm可以

**Comment by pdog18** [comment]
谢谢大佬的回复。不好意思再打扰一下您，因为我也是刚从 B 站了解到你这个神奇的工具，不太确定您说的 ldn_mitm 是不是需要破解才能用的，自己尝试搜索了一圈感觉只有破解了国行机才行，是吗?(很不死心的来求问大佬)🤣

**Comment by spacemeowx2** [comment]
ldn_mitm 需要配合自制固件使用, 我认为与你口中的“破解”表达的意思是一致的.

**Comment by pdog18** [comment]
谢谢
