### ISSUE TITLE
Ubuntu 20.04 gets the same issue as #134

### ISSUE THREAD

**Issue by Roadhog360** [spacemeowx2/switch-lan-play#140]
Title. #134 (which is a dupe of #100) happens on Ubuntu 20.04. Contrary to the comment posted on #100, this is __not__ ignorable. My friend is on the same server, yet cannot see my room when I create it. So this must be the issue.

Opening this basically to confirm it is not MacOS exclusive and is **_NOT_** ignorable.

**Comment by spacemeowx2** [comment]
lanplay relies on ARP spoofing (implemented at layer 2) to enable spoofing of multiple remote switches. So when your router has implementations such as client isolation and ARP firewalls, lanplay may not work. Don't just blame the program

**Comment by Roadhog360** [comment]
They demonstrate the same error.
In the end of the day, I was using the program incorrectly although it was originally erroring on its own.

**Comment by Roadhog360** [comment]
Edit: it was supposed to be #132
