### ISSUE TITLE
Can't compile on ubuntu arm64

### ISSUE THREAD

**Issue by rostomzer** [spacemeowx2/switch-lan-play#153]
When i try to compile this error appears

`ubuntu@ubuntu-arm64:~/Downloads/switch-lan-play-master$ cd build
ubuntu@ubuntu-arm64:~/Downloads/switch-lan-play-master/build$ cmake ..
-- Installing libuv via submodule
fatal: not a git repository (or any of the parent directories): .git
CMake Error at external/external.cmake:16 (add_subdirectory):
  The source directory

    /home/ubuntu/Downloads/switch-lan-play-master/external/libuv

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:36 (include)

CMake Error at external/external.cmake:17 (target_include_directories):
  Cannot specify include directories for target "uv_a" which is not built by
  this project.
Call Stack (most recent call first):
  CMakeLists.txt:36 (include)

error: src/unix/internal.h: No such file or directory
-- Installing uvw via submodule
fatal: not a git repository (or any of the parent directories): .git
CMake Error at external/external.cmake:38 (add_subdirectory):
  The source directory

    /home/ubuntu/Downloads/switch-lan-play-master/external/uvw

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:36 (include)

fatal: not a git repository (or any of the parent directories): .git
git describe --tags output is empty, set version to v0.2.0
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/Downloads/switch-lan-play-master/build/CMakeFiles/CMakeOutput.log".`

**Comment by spacemeowx2** [comment]
do you have git installed?

**Comment by spacemeowx2** [comment]
You must `git clone` this repository to build. Don't use zip of source code to build.
