### ISSUE TITLE
Mac support? 

### ISSUE THREAD

**Issue by thedonalddon** [spacemeowx2/switch-lan-play#2]
请问MAC上能否用Charles之类的软件实现代理？

**Comment by spacemeowx2** [comment]
需要支持 udp 的, charles 据我所知是 http 代理

**Comment by iamcco** [comment]
readme 不是写着支持mac吗:)

**Comment by spacemeowx2** [comment]
@iamcco lan-play 和直接上网是支持的, 这里说的是代理

**Comment by spacemeowx2** [comment]
但是 #1 实现后应该就能直接用 SOCKS5 代理

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/switch-lan-play/commit/c330b673d1698af47dfe68f6c5591ab71a4139f4 添加了代理支持
