### ISSUE TITLE
你好,我如果把客户端放在windows上运行,联机暗黑时流畅,如果把客户端在ubuntu上运行,就会很卡,这是什么问题?

### ISSUE THREAD

**Issue by snakwu** [spacemeowx2/switch-lan-play#30]
你好,我如果把客户端放在windows上运行,联机暗黑时流畅,如果把客户端在ubuntu上运行,就会很卡,这是什么问题?

**Comment by spacemeowx2** [comment]
What is your Ubuntu version?

**Comment by snakwu** [comment]
在windows10和ubuntu18.04连接的都是同一个lan-play server，但windows的速度要流畅好多，但如果用ubuntu来连接，延时大，速度慢，希望能解决一下，谢谢。。。

**Comment by Cubuss** [comment]
Are you running ubuntu in a virtual machine by any chance?

**Comment by snakwu** [comment]
我有虚拟机ubuntu server 18.04

**Comment by snakwu** [comment]
我有虚拟机ubuntu server 18.04

**Comment by snakwu** [comment]
我有虚拟机ubuntu server 18.04

**Comment by spacemeowx2** [comment]
速度缓慢的情况下 Ubuntu 是不是在虚拟机里运行的

**Comment by snakwu** [comment]
是的，我是在虚拟机上运行的

**Comment by snakwu** [comment]
用安卓卓手机来运行，也同样缓慢

**Comment by snakwu** [comment]
我server也是在虚拟机上，然后再用另一个虚拟机运行客户端，这样做到一连switch就可联网，不需开多台电脑，但是同一个在虚拟机的server，用电脑的win10运行客户端完全没问题，如果用另一台虚拟机运行客户端，就卡顿

**Comment by snakwu** [comment]
用安卓手机做热点，再用termux运行客户端，也同样卡顿

**Comment by Cubuss** [comment]
这可能是它缓慢的原因，尝试将虚拟机直接连接到网络

**Comment by snakwu** [comment]
虚拟机是直接桥接到物理网卡上的，不是用的虚拟网卡

**Comment by spacemeowx2** [comment]
The reason of terrible performances on Linux(see also: #30) has been found. And can be fixed by this commit 1f58b77.

Related issue: the-tcpdump-group/libpcap#550

But to make sure this change will not influence other platform(e.g Windows and Mac), we need test before merging into master.

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/switch-lan-play/commit/e4d5b67cd35e1edb505067dd179eba141fa7db6f
