### ISSUE TITLE
Armhf rockchip singleboard (Rock64)

### ISSUE THREAD

**Issue by S3phi40T** [spacemeowx2/switch-lan-play#32]
I have updated sources and can't compile server anymore :/ 
It worked earlier.
I'm using single board computer with Debian Stretch armhf (omv edition).

sephirot@Kamyk:~$ git clone https://github.com/spacemeowx2/switch-lan-play.git
Cloning into 'switch-lan-play'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1521 (delta 3), reused 7 (delta 2), pack-reused 1509
Receiving objects: 100% (1521/1521), 3.13 MiB | 2.39 MiB/s, done.
Resolving deltas: 100% (887/887), done.
sephirot@Kamyk:~$ cd switch-lan-play/server
sephirot@Kamyk:~/switch-lan-play/server$ npm run build

> switch-lan-play@1.0.0-alpha.2 build /srv/dev-disk-by-label-Malinka-Media/Home/                                                                                                                                                             sephirot/switch-lan-play/server
> tsc -p .

sh: 1: tsc: not found

npm ERR! Linux 4.4.132-1075-rockchip-ayufan-ga83beded8524
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.15.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! switch-lan-play@1.0.0-alpha.2 build: `tsc -p .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the switch-lan-play@1.0.0-alpha.2 build script 'tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the switch-lan-play packa                                                                                                                                                             ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs switch-lan-play
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls switch-lan-play
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in                                                                                                                                                             stall?

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/                                                                                                                                                             server/npm-debug.log
sephirot@Kamyk:~/switch-lan-play/server$ sudo npm install
[sudo] password for sephirot:
switch-lan-play@1.0.0-alpha.2 /srv/dev-disk-by-label-Malinka-Media/Home/sephirot                                                                                                                                                             /switch-lan-play/server
+-- @types/koa@2.0.47
| +-- @types/accepts@1.3.5
| +-- @types/cookies@0.7.1
| | +-- @types/connect@3.4.32
| | `-- @types/express@4.16.0
| |   +-- @types/body-parser@1.17.0
| |   +-- @types/express-serve-static-core@4.16.0
| |   | +-- @types/events@1.2.0
| |   | `-- @types/range-parser@1.2.3
| |   `-- @types/serve-static@1.13.2
| |     `-- @types/mime@2.0.0
| +-- @types/http-assert@1.3.0
| +-- @types/keygrip@1.0.1
| `-- @types/koa-compose@3.2.2
+-- @types/koa-router@7.0.35
+-- @types/koa2-cors@2.0.1
+-- @types/node@8.10.39
+-- koa@2.6.2
| +-- accepts@1.3.5
| | +-- mime-types@2.1.21
| | | `-- mime-db@1.37.0
| | `-- negotiator@0.6.1
| +-- cache-content-type@1.0.1
| | `-- ylru@1.2.1
| +-- content-disposition@0.5.3
| | `-- safe-buffer@5.1.2
| +-- content-type@1.0.4
| +-- cookies@0.7.3
| | `-- keygrip@1.0.3
| +-- debug@3.1.0
| | `-- ms@2.0.0
| +-- delegates@1.0.0
| +-- depd@1.1.2
| +-- destroy@1.0.4
| +-- error-inject@1.0.0
| +-- escape-html@1.0.3
| +-- fresh@0.5.2
| +-- http-assert@1.4.0
| | `-- deep-equal@1.0.1
| +-- http-errors@1.7.1
| | +-- inherits@2.0.3
| | +-- setprototypeof@1.1.0
| | `-- toidentifier@1.0.0
| +-- is-generator-function@1.0.7
| +-- koa-compose@4.1.0
| +-- koa-convert@1.2.0
| | +-- co@4.6.0
| | `-- koa-compose@3.2.1
| +-- koa-is-json@1.0.0
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- only@0.0.2
| +-- parseurl@1.3.2
| +-- statuses@1.5.0
| +-- type-is@1.6.16
| | `-- media-typer@0.3.0
| `-- vary@1.1.2
+-- koa-router@7.4.0
| +-- koa-compose@3.2.1
| | `-- any-promise@1.3.0
| +-- methods@1.1.2
| +-- path-to-regexp@1.7.0
| | `-- isarray@0.0.1
| `-- urijs@1.19.1
+-- koa2-cors@2.0.6
`-- typescript@3.2.2

npm WARN switch-lan-play@1.0.0-alpha.2 No description
npm WARN switch-lan-play@1.0.0-alpha.2 No repository field.
sephirot@Kamyk:~/switch-lan-play/server$ sudo npm run build

> switch-lan-play@1.0.0-alpha.2 build /srv/dev-disk-by-label-Malinka-Media/Home/                                                                                                                                                             sephirot/switch-lan-play/server
> tsc -p .

sephirot@Kamyk:~/switch-lan-play/server$ sudo npm run server

> switch-lan-play@1.0.0-alpha.2 server /srv/dev-disk-by-label-Malinka-Media/Home                                                                                                                                                             /sephirot/switch-lan-play/server
> node dist/udpserver.js

/srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/server/node_m                                                                                                                                                             odules/koa2-cors/dist/index.js:24
  return async function cors(ctx, next) {
               ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/dev-disk-by-label-Malinka-Media/Home/sephirot/sw                                                                                                                                                             itch-lan-play/server/dist/monitor.js:15:37)

npm ERR! Linux 4.4.132-1075-rockchip-ayufan-ga83beded8524
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
npm ERR! node v6.15.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! switch-lan-play@1.0.0-alpha.2 server: `node dist/udpserver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the switch-lan-play@1.0.0-alpha.2 server script 'node dist/ud                                                                                                                                                             pserver.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the switch-lan-play packa                                                                                                                                                             ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/udpserver.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs switch-lan-play
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls switch-lan-play
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/                                                                                                                                                             server/npm-debug.log

/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'server' ]
2 info using npm@3.10.10
3 info using node@v6.15.1
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle switch-lan-play@1.0.0-alpha.2~preserver: switch-lan-play@1.0.0-alpha.2
6 silly lifecycle switch-lan-play@1.0.0-alpha.2~preserver: no script for preserver, continuing
7 info lifecycle switch-lan-play@1.0.0-alpha.2~server: switch-lan-play@1.0.0-alpha.2
8 verbose lifecycle switch-lan-play@1.0.0-alpha.2~server: unsafe-perm in lifecycle true
9 verbose lifecycle switch-lan-play@1.0.0-alpha.2~server: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/s$
10 verbose lifecycle switch-lan-play@1.0.0-alpha.2~server: CWD: /srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/server
11 silly lifecycle switch-lan-play@1.0.0-alpha.2~server: Args: [ '-c', 'node dist/udpserver.js' ]
12 silly lifecycle switch-lan-play@1.0.0-alpha.2~server: Returned: code: 1  signal: null
13 info lifecycle switch-lan-play@1.0.0-alpha.2~server: Failed to exec server script
14 verbose stack Error: switch-lan-play@1.0.0-alpha.2 server: `node dist/udpserver.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid switch-lan-play@1.0.0-alpha.2
16 verbose cwd /srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/server
17 error Linux 4.4.132-1075-rockchip-ayufan-ga83beded8524
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
19 error node v6.15.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error switch-lan-play@1.0.0-alpha.2 server: `node dist/udpserver.js`
22 error Exit status 1
23 error Failed at the switch-lan-play@1.0.0-alpha.2 server script 'node dist/udpserver.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the switch-lan-play package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/udpserver.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs switch-lan-play
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls switch-lan-play
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by spacemeowx2** [comment]
update your node to version 8.0 or high

**Comment by S3phi40T** [comment]
THX!!
For future reference:
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
sudo apt install nodejs
