### ISSUE TITLE
[Error] Client err: -14

### ISSUE THREAD

**Issue by Ofdas23** [spacemeowx2/switch-lan-play#33]
-Latest build of lan play
-MacOS X
-Switch version: 6.2.0 ReiNX
-Switch settings: IP-Adress: 010.013.087.001; Subnetz-Maske: 255.255.000.000; 
Gateway: 010.013.037.001
DNS: Primary: 163.172.141.219; Secondary: 045.248.048.062
MTU: 1500
Terminal: 
sudo /Users/_username_/Desktop/lan-play 
--relay-server-addr is required
Input the relay server address [ domain/ip:port ]: [_Server-Adress-here_]
1. en0 (No description available)
	IP: [______________]
2. fw0 (No description available)
	IP: [none]
3. en1 (No description available)
	IP: [______________]
4. lo0 (No description available)
	IP: [127.0.0.1,]
Enter the interface number (1-4):3
Opening en1
[DEBUG]: filter: net 10.13.0.0/16
Get MAC: 0:1e:52:82:1c:c9
[DEBUG]: packet init buffer 0x1017ab520
Server IP: 178.254.26.56
pcap loop start
0x101ab5108 accept, connect 95.216.149.205:80
[ERROR]: client err: -14
[DEBUG]: read_cb -4095
0x101ab5108 accept, connect 95.216.149.205:80
[ERROR]: client err: -14

Nintendo Switch connects to router but it fails at connecting to the internet, with the error code (on Switch): 2110-3131 

Hello, 
Switch-Lan-Play worked perfectly fine, before I updated my switch from 6.1.0 to 6.2.0. I don´t know, why this issue is happening and I don´t know how to fix it. Can someone please help me? Thank you in advance!
Best regards.

**Comment by spacemeowx2** [comment]
It looks like you have two lan-play running. Make sure only one is running

**Comment by Ofdas23** [comment]
@spacemeowx2 I am sure one is running, but the strange part is, whenever I restart my Mac and don’t do anything except launching lan play, it works. It’s buggy but it works.
