### ISSUE TITLE
Add support for Win10Pcap and KM-TEST Loopback Adapter driver

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [spacemeowx2/switch-lan-play#37]
I'm using Win10Pcap alongside the Microsoft KM-TEST Loopback Adapter driver, which my Wi-Fi (my only connection with Internet access) is shared with. I cannot have a LAN connection on my PC due to not having access to my ISP's router via ethernet. lan-play.exe keeps saying "FATAL bad memory block" over and over again, and my Switch keeps failing to connect to the Internet with a DNS resolution error (I'm using Google DNS). When I install WinPcap in compatibility for Windows 7, no errors pop up on the PC side, but it doesn't appear to be doing anything, and my Switch still fails with a DNS resolution error. How can I fix this? Is there any way that I can play MHGU online with this tool?

**Comment by spacemeowx2** [comment]
what about using npcap: https://nmap.org/npcap/

**Comment by M1CR0H4CK3R** [comment]
> what about using npcap: https://nmap.org/npcap/

Thanks! That worked perfectly! I guess you can close this issue now if you want.
