### ISSUE TITLE
Server doesn't load on Windows

### ISSUE THREAD

**Issue by jlozes** [spacemeowx2/switch-lan-play#39]
Hi,

I've tried to launch the server but I've encountered an error (latest Github version of the project).

I've used Nodist to install Node.js and I have tried the commands listed on the "readme" of th Switch Lan Play project, the "npm install" and "npm run build" worked but the "npm start" or "npm run server" give me the errors listed on the "npm-debug.log" file attached to this message.

Thanks for your help.

[npm-debug.log](https://github.com/spacemeowx2/switch-lan-play/files/2717262/npm-debug.log)

**Comment by spacemeowx2** [comment]
upgrade your node to version >= 8.0

**Comment by jlozes** [comment]
Thanks, this has worked. Here are the commands for Nodist users:

```
nodist` add latest
nodist latest
nodist npm add latest
nodist npm latest
```

Then, the server build and launch itself without problems.

I'm closing this issue, thanks again, this was my first time with Node and NPM.
