### ISSUE TITLE
Request: Display users per game on /info endpoint

### ISSUE THREAD

**Issue by Gee19** [spacemeowx2/switch-lan-play#43]
Would be cool to display which games users are playing on the info endpoint. I know the capability isn't there yet but would be a neat feature.

**Comment by spacemeowx2** [comment]
It's hard to detect what games others are playing through the packet.

**Comment by spacemeowx2** [comment]
You could have a try

**Comment by technicgb** [comment]
What about just a text box for users to say what they are playing? Integration with discord or something.

**Comment by synepcice** [comment]
Hello. I suggest a Chat Window into a Gui integrated to the Lan Play software.
Discord is not easy to use (1300 Peoples and no one awnser cause no one is realy connected to the soft). When we use Lan Play , we can see 5 or 6 People truely connected (https://www.lan-play.com/), it would be nice to discuss with them only. (A Chat on the Gui Software would be fantastic).
