### ISSUE TITLE
更新0.1.0源码后，termux编译失败。

### ISSUE THREAD

**Issue by snakwu** [spacemeowx2/switch-lan-play#44]
换回0.0.7版的源码就正常编译，谢谢！

**Comment by snakwu** [comment]
![_1637690919_1548505314946_1548505315000_xg_0](https://user-images.githubusercontent.com/5343595/51787187-94bb4000-21a9-11e9-8c6a-922d2ee31b72.jpg)

**Comment by snakwu** [comment]
安卓系统是6.0

**Comment by spacemeowx2** [comment]
https://github.com/termux/termux-packages/blob/master/ndk-patches/ifaddrs.h

应该和这个有关, 不过讲道理程序里并没有用到相关的函数不应该被连接才对

**Comment by snakwu** [comment]
那个补丁怎么用,怎么才可以编译通过?

**Comment by snakwu** [comment]
好的，静候佳音

**Comment by jamilpardo** [comment]
Ayuda yo tambien tengo el mismo problema que el de la foto .

**Comment by jamilpardo** [comment]
Hola otra vez para solucionar el error de la foto que publico el amigo "snakwu ha " instale el comando clang. De la siguiente forma:
pkg install clang

Pero ahora me sale este otro mensaje :
Installing libuv via submodule
Submodule 'external/libuv' (https://github.com/libuv/libuv.git) registered for path 'external/libuv'
Cloning into '/data/data/com.termux/files/home/switch-lan-play/external/libuv'...
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 103
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/libuv/libuv.git' into submodule path '/data/data/com.termux/files/home/switch-lan-play/external/libuv' failed
Failed to clone 'external/libuv'. Retry scheduled
Cloning into '/data/data/com.termux/files/home..................


Prueben instalando el comando clang y despues publiquen si ustedes pudieron solucionarlo
