### ISSUE TITLE
Problem with cmake in Raspbian

### ISSUE THREAD

**Issue by fan3k** [spacemeowx2/switch-lan-play#45]
With command cmake ..

> pi@raspberrypi:~/switch-lan-play/build $ cmake ..
> -- The C compiler identification is GNU 6.3.0
> -- The CXX compiler identification is GNU 6.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check if the system is big endian
> -- Searching 16 bit integer
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of unsigned short
> -- Check size of unsigned short - done
> -- Using unsigned short
> -- Check if the system is big endian - little endian
> -- Installing libuv via submodule
> error: patch failed: src/unix/internal.h:60
> error: src/unix/internal.h: patch does not apply
> -- Installing uvw via submodule
> *
> * uvw v1.12.0 (Debug)
> * Copyright (c) 2016-2018 Michele Caini <michele.caini@gmail.com>
> *
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Found Threads: TRUE  
> -- Found Doxygen: /usr/local/bin/doxygen (found suitable version "1.8.16", minimum required is "1.8") 
> -- Found PCAP: /usr/lib/arm-linux-gnueabihf/libpcap.so  
> -- Configuring done
> CMake Error in src/CMakeLists.txt:
>   Target "lan-play" requires the language dialect "CXX17" (with compiler
>   extensions), but CMake does not know the compile flags to use to enable it.
> 
> 
> -- Generating done
> -- Build files have been written to: /home/pi/switch-lan-play/build

And "make":

> pi@raspberrypi:~/switch-lan-play/build $ sudo make
> Scanning dependencies of target base
> [  0%] Building C object base/CMakeFiles/base.dir/debug.c.o
> [  1%] Building C object base/CMakeFiles/base.dir/llog.c.o
> [  2%] Linking C static library libbase.a
> [  2%] Built target base
> Scanning dependencies of target lwip_lib
> [  4%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/udp.c.o
> [  4%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/memp.c.o
> [  5%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/init.c.o
> [  7%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/pbuf.c.o
> [  8%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/tcp.c.o
> [ 10%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/tcp_out.c.o
> [ 11%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/sys.c.o
> [ 12%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/netif.c.o
> [ 14%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/def.c.o
> [ 15%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/mem.c.o
> [ 17%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/tcp_in.c.o
> [ 17%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/stats.c.o
> [ 18%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ip.c.o
> [ 20%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/timeouts.c.o
> [ 21%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/inet_chksum.c.o
> [ 22%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv4/icmp.c.o
> [ 24%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv4/ip4.c.o
> [ 25%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv4/ip4_addr.c.o
> [ 27%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv4/ip4_frag.c.o
> [ 28%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/ip6.c.o
> [ 28%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/nd6.c.o
> [ 30%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/icmp6.c.o
> [ 31%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/ip6_addr.c.o
> [ 32%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/ip6_frag.c.o
> [ 34%] Linking C static library liblwip_lib.a
> [ 34%] Built target lwip_lib
> Scanning dependencies of target uv_a
> [ 35%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/fs-poll.c.o
> [ 37%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/idna.c.o
> [ 38%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/inet.c.o
> [ 40%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/strscpy.c.o
> [ 41%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/threadpool.c.o
> [ 42%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/timer.c.o
> [ 44%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/uv-common.c.o
> [ 45%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/uv-data-getter-setters.c.o
> [ 45%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/version.c.o
> [ 47%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/async.c.o
> [ 48%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/core.c.o
> [ 50%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/dl.c.o
> [ 51%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/fs.c.o
> [ 52%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/getaddrinfo.c.o
> [ 54%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/getnameinfo.c.o
> [ 55%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/loop-watcher.c.o
> [ 57%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/loop.c.o
> [ 57%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/pipe.c.o
> [ 58%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/poll.c.o
> [ 60%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/process.c.o
> [ 61%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/signal.c.o
> [ 62%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/stream.c.o
> [ 64%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/tcp.c.o
> [ 65%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/thread.c.o
> [ 67%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/tty.c.o
> [ 68%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/udp.c.o
> [ 68%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/proctitle.c.o
> [ 70%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/linux-core.c.o
> [ 71%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/linux-inotify.c.o
> [ 72%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/linux-syscalls.c.o
> [ 74%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/procfs-exepath.c.o
> [ 75%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/sysinfo-loadavg.c.o
> [ 77%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/sysinfo-memory.c.o
> [ 78%] Linking C static library libuv_a.a
> [ 78%] Built target uv_a
> Scanning dependencies of target uv_lwip
> [ 80%] Building C object uv_lwip/CMakeFiles/uv_lwip.dir/uv_lwip.c.o
> [ 81%] Linking C static library libuv_lwip.a
> [ 81%] Built target uv_lwip
> Scanning dependencies of target lan-play
> [ 82%] Building C object src/CMakeFiles/lan-play.dir/main.c.o
> [ 84%] Building C object src/CMakeFiles/lan-play.dir/pcaploop.c.o
> [ 85%] Building C object src/CMakeFiles/lan-play.dir/packet.c.o
> [ 87%] Building C object src/CMakeFiles/lan-play.dir/arp.c.o
> [ 88%] Building C object src/CMakeFiles/lan-play.dir/helper.c.o
> [ 90%] Building C object src/CMakeFiles/lan-play.dir/lan-client.c.o
> [ 90%] Building CXX object src/CMakeFiles/lan-play.dir/gateway.cpp.o
> [ 91%] Building CXX object src/CMakeFiles/lan-play.dir/proxy_direct.cpp.o
> [ 92%] Building CXX object src/CMakeFiles/lan-play.dir/proxy_socks5.cpp.o
> [ 94%] Building C object src/CMakeFiles/lan-play.dir/ipv4/ipv4.c.o
> [ 95%] Building C object src/CMakeFiles/lan-play.dir/ipv4/tcp.c.o
> [ 97%] Building C object src/CMakeFiles/lan-play.dir/ipv4/udp.c.o
> [ 98%] Building C object src/CMakeFiles/lan-play.dir/ipv4/icmp.c.o
> [100%] Linking CXX executable lan-play
> [100%] Built target lan-play
> pi@raspberrypi:~/switch-lan-play/build $ 

And im not have executable file "lan-play" in build folder.

**Comment by spacemeowx2** [comment]
it's in `./src/` folder now, so you should run it with `./src/lan-play`
