### ISSUE TITLE
arp attack

### ISSUE THREAD

**Issue by pwpwpw1122** [spacemeowx2/switch-lan-play#5]
how to defense arp attack?

**Comment by pwpwpw1122** [comment]
arp 攻击是违法行为。拿到攻击源也很简单。我现在拿到攻击源了。是不是可以报警？
还有arp 攻击防范有什么经验吗？还是客户机自己做防护？

**Comment by spacemeowx2** [comment]
这和这个项目有什么关系?

**Comment by pwpwpw1122** [comment]
那和你本人有没有关系呢？

**Comment by CoderNeko** [comment]
[The big crowd is watching everything!](https://github.com/spacemeowx2/switch-lan-play/issues/5)

**Comment by AngryPowman** [comment]
@pwpwpw1122 没觉得你的问题和这个项目有什么联系，这是站在道德制高点？不冷吗？

**Comment by zsxsoft** [comment]
“警察同志，我举报，我的NDS攻击了我的电脑”
