### ISSUE TITLE
Termux 0.72 build crashing with linker error

### ISSUE THREAD

**Issue by gut5** [spacemeowx2/switch-lan-play#53]
I'm following these instructions https://gist.github.com/spacemeowx2/b2f336489ce621c9d177db0fb35940f1
(Using the latest git master)

And also tried the ones from the gbatemp thread here https://gbatemp.net/threads/zero-to-smashing-local-wireless-online-ldn_mitm-guide.526228/

screenshot of error
![Screenshot_20190624-210614_Termux](https://user-images.githubusercontent.com/44514/60087226-81020e80-9734-11e9-848f-cc8d7478955d.png)

Lineage OS 16 (Android 9 Pie), Nexus 6 (32-bit ARM CPU, 3GB RAM). Latest Termux from Play Store (0.72)

**Comment by jamilpardo** [comment]
I have the same problem.
Help please.

**Comment by spacemeowx2** [comment]
The error might be related to issue https://github.com/termux/termux-packages/issues/3092

**Comment by deepweed1989** [comment]
It's not working on android pie and nobody os trying to make it working.

**Comment by jamilpardo** [comment]
Hola yo no tengo android 9 pero si tengo instalado android 8.1  en mi galaxy j7 prime; rooteado con magisk.  Pero si me aparece al final; despuea de ejecutar el (./ps4 )
esto :
Command ../switch-lan-play/build/lan-play not found
Check your spelling and try again
