### ISSUE TITLE
Run lan-play command on Alpine Linux

### ISSUE THREAD

**Issue by bao3** [spacemeowx2/switch-lan-play#6]
OS : Alpine Linux 3.8 x64
Library: libuv-dev, libpcap-dev
Issue:

When I run the command "lan-play" ,I got error , 
```
alpine:~# sh ./lan-play
./lan-play: line 1: ELF: not found
./lan-play: line 1: : not found
./lan-play: line 1: syntax error: unexpected word (expecting ")")

```

**Comment by spacemeowx2** [comment]
remove your sh before `./lan-play`, it's not a shell script!

**Comment by bao3** [comment]
Yes, I just typed " ./lan-play --remote...... " but it show the error " ./lan-play : no found " ( it did exist indeed)

**Comment by spacemeowx2** [comment]
That probably means the `lan-play` doesn't have execute permission, run `chmod +x ./lan-play`.

**Comment by bao3** [comment]
I did "chmod" at the early first time, without "chmod" I would get " Operation Not Permitted"

**Comment by spacemeowx2** [comment]
Or maybe it depends libc but alpine doesn't have. You'd better compile `lan-play` yourself.

**Comment by bao3** [comment]
Got it .
