### ISSUE TITLE
树莓派3b+ raspbian 编译后运行失败

### ISSUE THREAD

**Issue by chenweiwen07** [spacemeowx2/switch-lan-play#65]
# 运行日志有异常，switch连接日志有反应，但是连接失败
![image](https://user-images.githubusercontent.com/35797132/71552482-e2cf6800-2a38-11ea-93ac-91b044668c4f.png)
# sudo cmake ..
![image](https://user-images.githubusercontent.com/35797132/71552492-33df5c00-2a39-11ea-978b-ce4e5135806d.png)
# sudo make
![image](https://user-images.githubusercontent.com/35797132/71552504-7143e980-2a39-11ea-95f9-0e7ac2f74184.png)
![image](https://user-images.githubusercontent.com/35797132/71552512-8751aa00-2a39-11ea-953c-92b07e7ca0a8.png)

**Comment by spacemeowx2** [comment]
目测是同时连接了有线和无线造成mac冲突的问题. 可以尝试断开其中一个连接

**Comment by spacemeowx2** [comment]
目测是同时连接了有线和无线造成mac冲突的问题. 可以尝试断开其中一个连接

**Comment by chenweiwen07** [comment]
是用无线的连接，没插网线，不过没禁用有线，或者有没有参数可以指定网卡

**Comment by spacemeowx2** [comment]
如果是这样的话看日志switch是已经连上了, 并且作了2次UDP请求. 再检查一下DNS服务器设置

**Comment by chenweiwen07** [comment]
认真想想我是win10成功后再试树莓派的，switch记得没动那些配置，不过我周末回家再试试，到时再麻烦你了，感谢

**Comment by spacemeowx2** [comment]
如果Win10成功后马上测试树莓派需要注意2点:

1. 确保Switch关屏清空ARP缓存, 否则还会连接你的PC

2. 确保同一内网只有一个lanplay在运行, 多开会产生冲突

**Comment by chenweiwen07** [comment]
好的👌

**Comment by zzyyuanmi** [comment]
我这儿树莓派3b编译运行也是同样的情况。后来发现日志里的Socks5ProxyUdp是SOCKS5代理的问题，用--socks5-server-addr指定一个有效代理就能跑了。
但不加这个参数的话就会出现题图中的情况，和填了一个无效代理地址的表现相同，不知道是什么原因。在win10下就没有这个问题。

**Comment by spacemeowx2** [comment]
我发现这似乎是命令行解析的bug, 有空研究下

**Comment by i4s33u** [comment]
I tried to compile and run on my Pi 4 and ended up same situation, too :( DNS failed

**Comment by larryboylow** [comment]
我也面对同样的问题。用无线的连接。 win10 却没有这样的问题。

**Comment by GreatWizard** [comment]
I have no idea what you are saying (thanks google translation...) but you should consider to use the option `netif` to select the one interface which have access to internet. This solve the situation for me:
`sudo ./lan-play --relay-server-addr switch.lan-play.com:11451 --netif eth0`

**Comment by xyqkent** [comment]
termux编译后，也是出现［DEBUG] :Socks5ProxyUdp这个问题
在pc上ccproxy建了socks5代理后
./lan-play --relay-server-addr 129.204.119.249:11451 --socks5-server-addr 192.168.2.200:1080
依旧不行，学习楼上GreatWizard用netif指定接口，也是不行，烦恼中~~~

**Comment by spacemeowx2** [comment]
刚刚提交了修复, 问题出现在之前的master分支上对命令行参数的解析有bug, 就算不提交--socks5-server-addr也会进入socks5代理模式, 然而并没有有效的socks5代理存在导致无法联网.

这个问题是在支持ipv6的时候引入的, 但是之后并没有发布版本, 所以只影响从master编译的程序.
