### ISSUE TITLE
没有连接信息滚动，termux和PC都没有，之前在PC上是可以连接局域网的

### ISSUE THREAD

**Issue by Windy2233** [spacemeowx2/switch-lan-play#68]
突然就不能连接局域网，也没有连接信息，游戏里进入局域网也没有带L的WIFI图标，
![QQ图片20200128210450](https://user-images.githubusercontent.com/60390896/73266476-ead61f80-4211-11ea-914e-56081aa325f3.jpg)

**Comment by spacemeowx2** [comment]
一个局域网里不能同时开两个或以上的lan-play. 另外这也不是bug report, 我先close, 你可以继续留言

**Comment by Windy2233** [comment]
请问连接不上局域网，需要检查哪里呢？

**Comment by spacemeowx2** [comment]
重启设备试试, 这个问题多半是开了多个lan-play引起的

**Comment by Windy2233** [comment]
一楼的问题就不管了，用游侠…打开一个lan-play（没有多开）…游戏机用马车8进入局域网，连接等待界面大概1秒就结束了…然后暂停回桌面…wifi图标不带L，lan-play一直都没有连接信息，这种情况该检查哪里？游戏机内DNS一直都是解析失败（无论是能否连上局域网）

**Comment by spacemeowx2** [comment]
检查下路由器连的对不对. 不行的话用管理员权限运行试试

**Comment by Windy2233** [comment]
今天又尝试了几遍，第一次，用管理员权限运行，直接填入服务器信息，依然出现一楼截图的情况，但是莫名其妙的是游戏居然进入了局域网（lan-play没有信息滚动），因为游戏机WIFI图标带L，我可以确定是局域网，后来再尝试几遍，结果都一样wifi不带L，无论有无一楼截图的信息，下面这个截图是我用termux编译源码得到的，你看termux运行的lan-play是否有问题？提示全是fail??????
![Screenshot_20200130-135439_Termux](https://user-images.githubusercontent.com/60390896/73424951-33edb700-436b-11ea-9bfd-a3db127ee9ea.png)

**Comment by spacemeowx2** [comment]
termux运行是需要root的, 你没有按root运行
