### ISSUE TITLE
关于是不是arp攻击

### ISSUE THREAD

**Issue by pwpwpw1122** [spacemeowx2/switch-lan-play#7]
百度我的ID和我的提问有关系吗？对，我就是知识浅薄，我知识不浅薄也不会舔着脸来这里寻求帮助啊。或许我遇到的就不是arp攻击。您不愿意讲也可以。句句话火药味我是欠你钱了还是怎么？arp攻击有没有不知道。人身攻击先来了~可怕~~~

**Comment by spacemeowx2** [comment]
你应该把你遇到的情景拿出来提问而不是遇到一个输出去随意百度一番把百度到的东西拿来问。
就像你身体不舒服百度了一下以为得了癌症，就去找医生问他癌症怎么治，你不觉得可笑吗？

**Comment by pwpwpw1122** [comment]
当然可笑啊，我也会笑，因为值得庆幸，我得的不是癌症。人身体不舒服，我想百度百度这也是人之常情吧，毕竟不是每个人都懂得看病。最起码医生会告诉我得的什么病，需要不需要吃药什么的。没有医生会打开百度人肉我吧，也不会有医生因为我不懂医术而嘲笑我知识浅薄吧？可能会有，但是最起码我没遇到过，常人不会这样。

**Comment by spacemeowx2** [comment]
你说什么就是什么吧, 我没有人肉你的.

我是拿你的github id搜到了你开的群, 然后搜索聊天记录才知道的问题. 

你自己不提供问题细节要我搜索才能拿到然后还一边说我人肉你, 原issue还回复"那和你本人有没有关系呢？" 鬼知道你是什么心态

**Comment by spacemeowx2** [comment]
Block了, 看了影响心情. Github不是论坛, 不是给你这样用的.
