### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by Qaious** [spacemeowx2/switch-lan-play#72]
MacOS Catalina
ATMOSPHERE 0.10.3
OFW 9.1.0

switch-lan error

~ % /Users/____/Desktop/Switch\ Backup/lan-play-macos ; exit;
--relay-server-addr is required
Input the relay server address [ domain/ip:port ]:switch.lan-play.com:11451
Opening interfaces
[DEBUG]: open en0 fail
[DEBUG]: open p2p0 fail
[DEBUG]: open awdl0 fail
[DEBUG]: open llw0 fail
[DEBUG]: open utun0 fail
[DEBUG]: open utun1 fail
[DEBUG]: open lo0 fail
[DEBUG]: open bridge0 fail
[DEBUG]: open en1 fail
[DEBUG]: open en2 fail
[DEBUG]: open gif0 fail
[DEBUG]: open stf0 fail
pcap loop start
[DEBUG]: packet init buffer 0x10afbf5e0
Server IP: 149.91.81.201

Cannot connect switch (with right internet config) via mac.
No further prompt such as 'connecting ....' even if the switch indicated it is connected.

**Comment by spacemeowx2** [comment]
run as root

**Comment by ajs256** [comment]
@Qaious, you need to run as root, paste the following into a terminal (assuming the app is still in the same place):
```sh
cd Desktop/Switch\ Backup; sudo ./lan-play-macos
```
