### ISSUE TITLE
Cannot connect MacOS

### ISSUE THREAD

**Issue by Asi7ho** [spacemeowx2/switch-lan-play#73]
MacOS Catalina
SX OS 2.9.4 Beta
Switch-lan-play 0.2.1 installed via Homebrew

--relay-server-addr is required
Input the relay server address [ domain/ip:port ]:switch.lan-play.com:11451
Opening interfaces
[DEBUG]: open en0 ok
[DEBUG]: open p2p0 fail: datalink(12)
[DEBUG]: open awdl0 ok
[DEBUG]: open llw0 ok
[DEBUG]: open utun0 fail: datalink(0)
[DEBUG]: open utun1 fail: datalink(0)
[DEBUG]: open lo0 fail: datalink(0)
[DEBUG]: open bridge0 ok
[DEBUG]: open en1 ok
[DEBUG]: open en2 ok
[DEBUG]: open en3 ok
[DEBUG]: open en4 ok
[DEBUG]: open gif0 fail: datalink(0)
[DEBUG]: open stf0 fail: datalink(0)
[DEBUG]: open ap1 ok
pcap loop start
[DEBUG]: packet init buffer 0x10386bb30
Server IP: 149.91.81.201
[DEBUG]: uv_pcap_interf_sendpacket failed -1
[DEBUG]: uv_pcap_interf_sendpacket failed -1
[DEBUG]: uv_pcap_interf_sendpacket failed -1
[DEBUG]: uv_pcap_interf_sendpacket failed -1
...

I have no other prompt than "[DEBUG]: uv_pcap_interf_sendpacket failed -1" and cannot connect swith to internet via mac.

**Comment by spacemeowx2** [comment]
I haven't upgrade to Catalina so I can not reproduce this problem.

Is this happened on Mojave before? Or only happen on Catalina?

**Comment by Asi7ho** [comment]
I haven’t test switch-lan-play on Majove so I don’t know if it only happen on Catalina.
I think the problem is from my Internet provider (public access like in an hotel) that blocks this kind of procedure.
I tried with another Internet provider and everything works 👍

**Comment by mrh270188** [comment]
This happens to me to. Anything I can do about it?

**Comment by jzarca01** [comment]
+1, tried both building from sources on macOS Catalina and raspbian jessie with libraries up to date

**Comment by poetL** [comment]
+1 in  catalina , in another same macos (same catalina) ,  this not happen

**Comment by jzarca01** [comment]
I found out that this actually doesn't prevent you from playing

Here's what I wrote for Animal Crossing : 
- make sure "Internet Local Play" is enabled in sxos settings
- make sure you entered the right network settings on your switch (with MTU 1500 for me)
- in your terminal in your lan-play folder enter "sudo ./lan-play-macos" and enter the server you want to join
- make sure your firewall is deactivated
- what i found working for me is first you open the gates to everyone then you can change your mind and travel

**Comment by jzarca01** [comment]
@spacemeowx2 what rules should I add to the firewall so that It can work ?
