### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by eidan99** [spacemeowx2/switch-lan-play#75]
can you do something about animal crossing new horizons? we can find each other but can't connect

**Comment by spacemeowx2** [comment]
it's not a forum.

**Comment by eidan99** [comment]
oh sorry mate,my bad i'm mortified,just wanted to ask you to check it out :( (sorry again) 


Inviato da Yahoo Mail. Scarica l'app 

    Il giovedì 19 marzo 2020, 15:53:19 CET, imspace <notifications@github.com> ha scritto:  
 
 


it's not a forum.
