### ISSUE TITLE
在配置服务器的时候，运行npm install的时候报错

### ISSUE THREAD

**Issue by wzcnly** [spacemeowx2/switch-lan-play#76]
root@duoduolanplay:~/switch-lan-play/server# npm install
npm WARN switch-lan-play@1.0.0-alpha.2 No description
npm WARN switch-lan-play@1.0.0-alpha.2 No repository field.

显示以上代码有解决方案么？ 
用的centos7和debian 9都遇到这个问题....是那里弄错了？

**Comment by spacemeowx2** [comment]
WARNING不是报错, 只是package.json部分字段没填
