### ISSUE TITLE
DNS resolution fails on non-Windows machines

### ISSUE THREAD

**Issue by NovaPhoenix** [spacemeowx2/switch-lan-play#77]
While running the client built from latest commit on Fedora 31, this is what I get as output:
```
Interface not specified, opening all interfaces
[DEBUG]: open enp2s0 ok
[DEBUG]: open wlp1s0 ok
[DEBUG]: open lo fail: get all zero mac
[DEBUG]: open any fail: datalink(113)
[DEBUG]: open virbr0 ok
[DEBUG]: open bluetooth-monitor fail: datalink(254)
[DEBUG]: open nflog fail: datalink(239)
[DEBUG]: open nfqueue fail: datalink(228)
[DEBUG]: open bluetooth0 fail: datalink(201)
[DEBUG]: open usbmon0 fail: datalink(220)
[DEBUG]: open usbmon1 fail: datalink(220)
[DEBUG]: open usbmon2 fail: datalink(220)
[DEBUG]: open virbr0-nic fail
pcap loop start
[DEBUG]: packet init buffer 0x6f4220
Server IP: redacted
[DEBUG]: Socks5ProxyUdp
[DEBUG]: Socks5ProxyUdp
[DEBUG]: Socks5ProxyUdp
[DEBUG]: Socks5ProxyUdp
[DEBUG]: ~Socks5ProxyUdp
[DEBUG]: ~Socks5ProxyUdp
[DEBUG]: Socks5ProxyUdp
[DEBUG]: Socks5ProxyUdp
```
And the socksproxy lines keep repeating. On my console, connection tests fail with 2110-3127 "could not perform dns name resolution". A friend of mine reported having the same issue on macOS. I have tried setting up the lan play server myself, setting up my own dns server, and using a public dns server to no avail.

**Comment by PhazonicRidley** [comment]
I have experienced this as well and I was on windows, I had the usual output of the client saying that it was connected. I was trying with 90dns

**Comment by spacemeowx2** [comment]
It should be the same reason in this issue: #65

Please pull from master and compile again. Latest commit fixes the bug
