### ISSUE TITLE
anyway to make this compatible with sysdvr?

### ISSUE THREAD

**Issue by borocode** [spacemeowx2/switch-lan-play#83]
hi I asked the sysdvr dev on gbatemp if there was anything i could do to get sysdvr and lan play working together docked. tried both of his ideas but no real luck. he mentions something about adding an exception for port 6666. is this something thats possible? 

[permalink to exelix11's reply on gbatemp](https://gbatemp.net/threads/sysdvr-stream-gameplay-directly-to-a-pc.550616/page-13#post-8994346)

**Comment by spacemeowx2** [comment]
you can add a ip to your interface like this picture. and your PC will be able to access your Switch via `10.13.x.y`

![ip](https://user-images.githubusercontent.com/8019167/78048016-b0246b00-73ab-11ea-8e6b-39172df4852b.png)

**Comment by spacemeowx2** [comment]
btw it is dangerous to expose the port when using switch-lan-play. Anyone on the same server can access Switch's port 6666.

**Comment by borocode** [comment]
> you can add a ip to your interface like this picture. and your PC will be able to access your Switch via `10.13.x.y`
> 
> ![ip](https://user-images.githubusercontent.com/8019167/78048016-b0246b00-73ab-11ea-8e6b-39172df4852b.png)

you're a God. Thank you, got it working!

**Comment by Rei-rahul** [comment]
> you can add a ip to your interface like this picture. and your PC will be able to access your Switch via `10.13.x.y`
> 
> ![ip](https://user-images.githubusercontent.com/8019167/78048016-b0246b00-73ab-11ea-8e6b-39172df4852b.png)

Do you know how to do this on Mac? I can't get it working
