### ISSUE TITLE
动森可以用吗

### ISSUE THREAD

**Issue by Inspiring26** [spacemeowx2/switch-lan-play#84]
Can I use it for Animal Crossing?

**Comment by spacemeowx2** [comment]
可

**Comment by Inspiring26** [comment]
怎么用呢？你们试验过吗，听说动森是机器自己创建热点，需要破解才能用吗？

**Comment by Inspiring26** [comment]
> 可

怎么用呢？你们试验过吗，听说动森是机器自己创建热点，需要破解才能用吗？

**Comment by Inspiring26** [comment]
@spacemeowx2  怎么用呢？你们试验过吗，听说动森是机器自己创建热点，需要破解才能用吗？谢谢！

**Comment by spacemeowx2** [comment]
是的, 正版不能用.
