### ISSUE TITLE
cmake Error & make Error

### ISSUE THREAD

**Issue by ray1025** [spacemeowx2/switch-lan-play#86]
# cmake ..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /opt/bin/cc
-- Check for working C compiler: /opt/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/bin/c++
-- Check for working CXX compiler: /opt/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Installing libuv via submodule
Submodule 'external/libuv' (https://github.com/libuv/libuv.git) registered for path 'external/libuv'
Cloning into '/volume1/tool/switch-lan-play/external/libuv'...
Submodule path 'external/libuv': checked out '274f2bd3b70847cadd9a3965577a87e666ab9ac3'
error: patch failed: src/unix/internal.h:60
error: src/unix/internal.h: patch does not apply
-- Installing uvw via submodule
Submodule 'external/uvw' (https://github.com/skypjack/uvw.git) registered for path 'external/uvw'
Cloning into '/volume1/tool/switch-lan-play/external/uvw'...
Submodule path 'external/uvw': checked out '183ebc03331c7c92f8eaded42f3d262fbecce37a'
*
* uvw v1.12.0 (Debug)
* Copyright (c) 2016-2018 Michele Caini <michele.caini@gmail.com>
*
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.8")
-- Found PCAP: /volume1/@optware/lib/libpcap.so
-- Configuring done
-- Generating done
-- Build files have been written to: /volume1/tool/switch-lan-play/build

# make
Scanning dependencies of target base
[  0%] Building C object base/CMakeFiles/base.dir/debug.c.o
[  1%] Building C object base/CMakeFiles/base.dir/llog.c.o
[  2%] Linking C static library libbase.a
[  2%] Built target base
Scanning dependencies of target lwip_lib
[  4%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/udp.c.o
[  5%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/memp.c.o
[  7%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/init.c.o
[  7%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/pbuf.c.o
[  8%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/tcp.c.o
[  9%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/tcp_out.c.o
[ 11%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/sys.c.o
[ 12%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/netif.c.o
[ 14%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/def.c.o
[ 14%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/mem.c.o
[ 15%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/tcp_in.c.o
[ 16%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/stats.c.o
[ 18%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ip.c.o
[ 19%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/timeouts.c.o
[ 21%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/inet_chksum.c.o
[ 22%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv4/icmp.c.o
[ 22%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv4/ip4.c.o
[ 23%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv4/ip4_addr.c.o
[ 25%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv4/ip4_frag.c.o
[ 26%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/ip6.c.o
[ 28%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/nd6.c.o
[ 29%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/icmp6.c.o
[ 29%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/ip6_addr.c.o
[ 30%] Building C object lwip/CMakeFiles/lwip_lib.dir/src/core/ipv6/ip6_frag.c.o
[ 32%] Linking C static library liblwip_lib.a
[ 32%] Built target lwip_lib
Scanning dependencies of target uv_a
[ 33%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/fs-poll.c.o
[ 35%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/idna.c.o
[ 36%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/inet.c.o
[ 36%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/strscpy.c.o
[ 38%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/threadpool.c.o
[ 39%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/timer.c.o
[ 40%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/uv-common.c.o
[ 42%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/uv-data-getter-setters.c.o
[ 43%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/version.c.o
[ 43%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/async.c.o
[ 45%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/core.c.o
[ 46%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/dl.c.o
[ 47%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/fs.c.o
[ 49%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/getaddrinfo.c.o
[ 50%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/getnameinfo.c.o
[ 52%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/loop-watcher.c.o
[ 52%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/loop.c.o
[ 53%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/pipe.c.o
[ 54%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/poll.c.o
[ 56%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/process.c.o
[ 57%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/signal.c.o
[ 59%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/stream.c.o
[ 59%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/tcp.c.o
[ 60%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/thread.c.o
[ 61%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/tty.c.o
[ 63%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/udp.c.o
[ 64%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/proctitle.c.o
[ 66%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/linux-core.c.o
[ 67%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/linux-inotify.c.o
[ 67%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/linux-syscalls.c.o
[ 69%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/procfs-exepath.c.o
[ 70%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/sysinfo-loadavg.c.o
[ 71%] Building C object external/libuv/CMakeFiles/uv_a.dir/src/unix/sysinfo-memory.c.o
[ 73%] Linking C static library libuv_a.a
[ 73%] Built target uv_a
Scanning dependencies of target uv_lwip
[ 74%] Building C object uv_lwip/CMakeFiles/uv_lwip.dir/uv_lwip.c.o
[ 76%] Linking C static library libuv_lwip.a
[ 76%] Built target uv_lwip
Scanning dependencies of target lan-play
[ 77%] Building C object src/CMakeFiles/lan-play.dir/main.c.o
[ 78%] Building C object src/CMakeFiles/lan-play.dir/lan-play.c.o
[ 80%] Building CXX object src/CMakeFiles/lan-play.dir/pcaploop.cpp.o
[ 80%] Building C object src/CMakeFiles/lan-play.dir/packet.c.o
[ 81%] Building C object src/CMakeFiles/lan-play.dir/arp.c.o
[ 83%] Building C object src/CMakeFiles/lan-play.dir/helper.c.o
[ 84%] Building C object src/CMakeFiles/lan-play.dir/lan-client.c.o
[ 85%] Building CXX object src/CMakeFiles/lan-play.dir/gateway.cpp.o
[ 87%] Building CXX object src/CMakeFiles/lan-play.dir/proxy_direct.cpp.o
[ 88%] Building CXX object src/CMakeFiles/lan-play.dir/proxy_socks5.cpp.o
[ 88%] Building C object src/CMakeFiles/lan-play.dir/sha1.c.o
[ 90%] Building C object src/CMakeFiles/lan-play.dir/ipv4/ipv4.c.o
[ 91%] Building C object src/CMakeFiles/lan-play.dir/ipv4/tcp.c.o
[ 92%] Building C object src/CMakeFiles/lan-play.dir/ipv4/udp.c.o
[ 94%] Building C object src/CMakeFiles/lan-play.dir/ipv4/icmp.c.o
[ 95%] Building CXX object src/CMakeFiles/lan-play.dir/rpc/rpc.cpp.o
[ 95%] Building CXX object src/CMakeFiles/lan-play.dir/rpc/lan-play.cpp.o
[ 97%] Building CXX object src/CMakeFiles/lan-play.dir/rpc/rpc-server.cpp.o
[ 98%] Building CXX object src/CMakeFiles/lan-play.dir/rpc/rpc-ws-server.cpp.o
[100%] Linking CXX executable lan-play
../external/libuv/libuv_a.a(signal.c.o): In function `uv__signal_global_init':
signal.c:(.text+0x1474): undefined reference to `pthread_atfork'
../external/libuv/libuv_a.a(threadpool.c.o): In function `init_once':
threadpool.c:(.text+0xa68): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
src/CMakeFiles/lan-play.dir/build.make:568: recipe for target 'src/lan-play' failed
make[2]: *** [src/lan-play] Error 1
CMakeFiles/Makefile2:389: recipe for target 'src/CMakeFiles/lan-play.dir/all' failed
make[1]: *** [src/CMakeFiles/lan-play.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hsuanpai** [comment]
How can I fix the below error when I compile under RPI (Buster)? 
-- Installing libuv via submodule
Submodule 'external/libuv' (https://github.com/libuv/libuv.git) registered for path 'external/libuv'
Submodule path 'external/libuv': checked out '274f2bd3b70847cadd9a3965577a87e666ab9ac3'
error: patch failed: src/unix/internal.h:60
error: src/unix/internal.h: patch does not apply
