### ISSUE TITLE
lan-play-win64 (0.2.1)

### ISSUE THREAD

**Issue by ray1025** [spacemeowx2/switch-lan-play#87]
Message appears during use

FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
[DEBUG]: IConnection::IConnection
[DEBUG]: TcpConnection::onConnection
FATAL Bad Memory Block.
[DEBUG]: ptcp->onConnect
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.

**Comment by spacemeowx2** [comment]
please reinstall winpcap or npcap with compatible mode. Don't use `Win10Pcap`

**Comment by ray1025** [comment]
ok,it's working.

**Comment by ray1025** [comment]
[DEBUG]: IConnection::IConnection
[DEBUG]: TcpConnection::onConnection
[DEBUG]: ptcp->onConnect
[DEBUG]: lwip->onClose
[DEBUG]: IConnection::~IConnection
[DEBUG]: IConnection::IConnection
[DEBUG]: TcpConnection::onConnection
[DEBUG]: ptcp->onConnect
[DEBUG]: ptcp->onClose 0 Unknown system error 0
[DEBUG]: IConnection::~IConnection

**Comment by ray1025** [comment]
ok,it is working.

[DEBUG]: IConnection::IConnection
[DEBUG]: TcpConnection::onConnection
[DEBUG]: ptcp->onConnect
[DEBUG]: lwip->onClose
[DEBUG]: IConnection::~IConnection
[DEBUG]: IConnection::IConnection
[DEBUG]: TcpConnection::onConnection
[DEBUG]: ptcp->onConnect
[DEBUG]: ptcp->onClose 0 Unknown system error 0
[DEBUG]: IConnection::~IConnection

**Comment by darkel86** [comment]
for me lan play work with winpcap but switch can't connect 
with npcap lan-play.exe crashes
