### ISSUE TITLE
如何将客户端程序放进openwrt中 让他自己运行 配个另外一个GUI项目

### ISSUE THREAD

**Issue by luuziiyoo** [spacemeowx2/switch-lan-play#88]
![1](https://user-images.githubusercontent.com/10737650/78741414-db9aed00-798b-11ea-9956-f5e6626122b5.jpg)

提到需要预装客户端主程序，这个GUI已经写进路由器了 能看到该界面，但是没有客户端程序的支撑，不知道怎么把这个主程序编译进路由器

**Comment by omegatao** [comment]
@luuziiyoo 请问这个问题是怎么解决的呢？我也编译好了luci界面，但是目前缺少switch-lan-play导致没办法使用
