### ISSUE TITLE
README: 使用Npcap替换WinPcap

### ISSUE THREAD

**Issue by littlecxm** [spacemeowx2/switch-lan-play#93]
建议：
WinPcap项目已经停止维护，Npcap提供WinPcap兼容模式
https://nmap.org/npcap/#download
![image](https://user-images.githubusercontent.com/16154023/79862276-7376ed00-8408-11ea-8b74-5bbf7a60213e.png)

**Comment by spacemeowx2** [comment]
可以提交PR, 需要重点标出必须勾选兼容模式, 否则会出错
